config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'

  resources :groups do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = "更新成功"
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:alert] = "删除成功"
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!

def new
  @group = Group.find(params[:group_id])
  @post = Post.new
end

def create
  @group = Group.find(params[:group_id])
  @post = Post.new(post_params)
  @post.group = @group
  @post.user = current_user

  if @post.save
    redirect_to(group_path(@group))
  else
    render :new
  end
end

private

def post_params
  params.require(:post).permit(:content)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes.helper.rb
module FlashesHelper
FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASS_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails113
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>笑飞飞加油~~</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 113</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("登录", new_user_session_path, class: "btn btn-sm") %></li>
                <li><%= link_to("注册", new_user_registration_path, class: "btn btn-sm") %></li>
              <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Hi, <%= current_user.email %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
                </ul>
              </li>
             <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 class="text-center">编辑讨论版</h2>
  <hr>
  <%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
    <%= f.submit "Submit", class: "btn btn-primary text-center", data: {disable_with: "Submiting..."} %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">

<div class="indexheader">
  <%= link_to("New Group", new_group_path, class: "btn btn-primary pull-right") %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td>#</td>
        <td><%= link_to(group.title, group_path(group)) %></td>
        <td><%= group.description %></td>
        <td>
          <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default") %>
          <%= link_to("Delete", group_path(group), method: :delete, class: "btn btn-sm btn-default", data: {confirm: "Are you sure?"}) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 class="text-center">新增讨论版</h2>
  <hr>
  <%= simple_form_for @group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submiting..."} %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <p><%= @group.title %></p>
  <%= link_to("Write a Post", new_group_post_path（@group), class: "btn btn-primary") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails113</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/posts/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2 class="text-center">新增文章</h2>
  <hr>
  <%= simple_form_for [@group,@post] do |f| %>
    <%= f.input :content, input_html: { class: "form-control"} %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>